[package]
name = "rrt-gmt"
version = "0.1.0"
authors = ["thibault <thibault.barbie@free.fr>"]

[dependencies]
rrt = "0.1.0"
rand = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rusty-machine ="0.5.4"
nalgebra = "*"
kdtree = "0.3.1"
log = "0.3.8"
env_logger = "0.4.3"
indicatif = "*"